<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>NotionPad</RootNamespace>
    <AssemblyName>NotionPad</AssemblyName>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>notepad.ico</ApplicationIcon>
    <Version>0.0.0</Version>
    <AssemblyVersion>0.0.0.0</AssemblyVersion>
    <FileVersion>0.0.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="notepad.png" />
    <None Include="notepad.ico" />
  </ItemGroup>

</Project>
